USE sakila;
SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
-- 1 Number of films per category
SELECT film.title , category.name 
FROM film
JOIN film_category
USING (film_id)
JOIN category
USING (category_id) 
GROUP BY film.title;
 
-- 2 The store ID, city, and country for each store
SELECT store.store_id , city.city , country.country
FROM store
JOIN address
USING (address_id)
JOIN city
USING (city_id)
JOIN country
USING (country_id)
GROUP BY store.store_id;

-- 3 Total revenue generated by each store in dollars
SELECT store.store_id , sum(payment.amount) As total_revenue
FROM store
JOIN customer 
USING (store_id)
JOIN payment
USING(customer_id)
GROUP by store_id;

-- 4 The average running time of films for each category
SELECT  category.name , AVG(film.length)
FROM film
JOIN film_category
USING (film_id)
JOIN category
USING (category_id)
GROUP BY category.name;



